#application: {{app_id}}
#version: 1
runtime: python27
api_version: 1
threadsafe: False

handlers:
- url: /vi/s
  static_dir: vi
- url: /static
  static_dir: static
- url: /resources
  static_dir: server/resources
- url: /_tasks
  script: {{app_id}}.application
- url: /admin/user/getAuthMethod
  script: {{app_id}}.application
- url: /admin/.*
  script: {{app_id}}.application
- url: /vi.*
  script: {{app_id}}.application
- url: /favicon.ico
  static_files: static/meta/favicon.ico
  upload: favicon.ico
- url: /robots.txt
  static_files: static/meta/robots.txt
  upload: robots.txt
- url: /.*
  script: {{app_id}}.application

libraries:
- name: jinja2
  version: latest
- name: pytz
  version: latest

inbound_services:
- warmup

builtins:
- deferred: on
